definitions:
  pkg.KBAddDataInstruct:
    properties:
      Create:
        type: boolean
      KBName:
        type: string
      data:
        items:
          type: string
        type: array
    type: object
  pkg.MessageInstruct:
    properties:
      KB:
        type: boolean
      KBName:
        type: string
      Message:
        type: string
    type: object
  pkg.MessageResponse:
    properties:
      Context:
        items:
          type: string
        type: array
      Query:
        type: string
      Response:
        type: string
    type: object
info:
  contact: {}
paths:
  /knowledge-base:
    post:
      consumes:
      - application/json
      description: Add string data to a knwoledge base, it creates the KB if the flag
        is set
      parameters:
      - description: Data to add to the KB
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/pkg.KBAddDataInstruct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: KB does not exist
          schema:
            type: string
      summary: Add data to a knowledge base
      tags:
      - knowledge-base
  /knowledge-base/{KBName}:
    post:
      consumes:
      - application/json
      description: Create a new knowledge base
      parameters:
      - description: KBName
        in: path
        name: KBName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: KB already exists
          schema:
            type: string
      summary: Create a new knowledge base
      tags:
      - knowledge-base
  /message:
    post:
      consumes:
      - application/json
      description: Send a one-shot message to get a response
      parameters:
      - description: Message to send
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/pkg.MessageInstruct'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.MessageResponse'
        "400":
          description: Error sending message
          schema:
            type: string
      summary: Send a one-shot message
      tags:
      - chat
swagger: "2.0"
