local: true
echo:
  port: "1323"
  local: true
chroma:
  base-url: "http://127.0.0.1:8000"
  embedd-url: "http://127.0.0.1:1234/v1/embeddings"
  model: "text-embedding-granite-embedding-278m-multilingual"
  max-values: 10
model:
  model: "deepseek-r1-distill-llama-8b@q6_k"
  model-url: "http://localhost:1234/v1/"
store:
  store-path: "../store"